UTC_Time = 8 -- JAM DI KOTAMU SEKARANG (Format 24 Jam)
UseMethod = true
SpamText = true
DelayRecon = 15000 --JEDA RECONNECT
delayworld = 7500 -- DELAY MASUK DOOR
delayplace = 115 -- DELAY PLACE
delaypnb = 165 -- DELAY PNB
MinItemPack = 3
JedaHW = 10
delayht = 110 -- DELAY HARVEST
delayplant = 110 -- DELAY PLANT
HW_Exit = true
SimplePinghook = true
IgnoreGems_PTHT = false
WorldPack = {"xtmnro"}
