UTC_Time = 8 -- JAM DI KOTAMU SEKARANG (Format 24 Jam)
UseMethod = true
SpamText = true
GrindingOD = true
DelayRecon = 15000 --JEDA RECONNECT
delayworld = 5000 -- DELAY MASUK DOOR
delayplace = 115 -- DELAY PLACE
delaypnb = 165 -- DELAY PNB
MinItemPack = 3
JedaHW = 2
delayht = 110 -- DELAY HARVEST
delayplant = 200 -- DELAY PLANT
HW_Exit = false
SimplePinghook = true
IgnoreGems_PTHT = false
